# Use a imagem oficial do PHP com Apache
FROM php:7.4-apache

# Copie os arquivos do projeto para o diretório padrão do Apache
COPY . /var/www/html/

# Instale as extensões necessárias do PHP
RUN docker-php-ext-install mysqli

# Exponha a porta 80
EXPOSE 80